// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using codeFirstNV.Data;

#nullable disable

namespace codeFirstNV.Migrations
{
    [DbContext(typeof(codeFirstNVContext))]
    partial class codeFirstNVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("codeFirstNV.Models.congty", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("congty");
                });

            modelBuilder.Entity("codeFirstNV.Models.nhanvien", b =>
                {
                    b.Property<int>("IdNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNV"));

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idphongban")
                        .HasColumnType("int");

                    b.Property<int>("tuoi")
                        .HasColumnType("int");

                    b.HasKey("IdNV");

                    b.ToTable("nhanvien");
                });

            modelBuilder.Entity("codeFirstNV.Models.phongban", b =>
                {
                    b.Property<int>("Idphongban")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idphongban"));

                    b.Property<string>("Namephongban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idcongty")
                        .HasColumnType("int");

                    b.HasKey("Idphongban");

                    b.ToTable("phongban");
                });
#pragma warning restore 612, 618
        }
    }
}
